using System.Threading.Channels;
using Content.Client.UserInterface.Controls;
using Content.Shared._WL.MetamorphosisSlime;
using Content.Shared.Radio.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._WL.MetamorphosisSlime.Ui;

[GenerateTypedNameReferences]
public sealed partial class MetamorphosisSlimeMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    //public event Action<bool>? OnMicPressed;
    //public event Action<bool>? OnSpeakerPressed;
    //public event Action<string>? OnChannelSelected;

    private readonly List<string> _morph = new();


    public MetamorphosisSlimeMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Update(Entity<MetamorphosisSlimeComponent> entity)
    {

        //for (var i = 0; i < entity.Comp.Morph.Count; i++)
        //{
        //    var morph = entity.Comp.Morph[i];

        //}



        if (entity.Comp.Morph.Count == 0)
        {
            MetamorphOptions.AddItem("Нету объектов для превращения", 0);
            MetamorphOptions.Select(0);
        }
    }
}

