using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using System.Linq;

namespace Content.Client._WL.DynamicText;

[GenerateTypedNameReferences]
public sealed partial class DynamicTextWindow : FancyWindow
{
    public DynamicTextWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
